Improvement: Added .env.example file
otaviolemos/thewisedev-mailing pull request #8
Opened 2022-03-22 15:18 UTC by NitoBa

The projects that  use environment variables usually have a `.env.example` file in root of their projects to show to devs 
what are the environment variables are used on project

2022-03-26 14:11 UTC, vrmartins requested changes

2022-03-26 14:11 UTC, vrmartins commented on .env.example
> +PORT=
```suggestion
PORT=

```

2022-03-27 20:38 UTC, vrmartins approved these changes

2022-08-05 17:11 UTC, henriquenery1 approved these changes
Good improvement

2022-08-16 03:17 UTC, closed without merging